export const validationMessage = (label?: string) => ({
  200: () => `Berhasil`,
  201: () => `Berhasil dibuat`,
  402: () => `Kolom tidak valid`,
  400: () => `Mohon periksa inputan Anda`,
  401: () => `Tidak punya akses`,
  404: () => `${label || "Data"} tidak ditemukan`,
  408: () => `Mohon periksa koneksi internet Anda!`,
  500: () => `Terjadi kesalahan server`,
  failedCreate: `Gagal membuat ${label || "form"}. Mohon periksa form Anda.`,
  failedUpdate: `Gagal mengupdate ${label || "form"}. Mohon periksa form Anda.`,
  unstableNetwork: `Koneksi internet tidak stabil`,
  noNetwork: `Tidak ada koneksi internet`,
  unstableNetworkDesc: `Terjadi kesalahan dengan koneksi internet Anda. Mohon pastikan Anda terkoneksi dengan internet dan reload browser Anda`,
  required: () => `${label} wajib diisi`,
  invalidField: () => `Format ${label} tidak valid`,
  minChar: (length: number) => `${label} harus minimal ${length} karakter`,
  duplicateValue: `${label || "Nilai ini"} sudah digunakan`,
  updated: `${label || "Data"} berhasil diupdate`,
  deleted: `${label || "Data"} berhasil dihapus`,
  min: (min: number) => `Minimal ${label} adalah ${min}`,
  max: (max: number) => `Maksimal ${label} adalah ${max}`,
});
